- name: Install packages
  hosts: webapp2
  remote_user: root
  become: yes
  # vars_files: playbook3_vars.yml
  vars:
    packages:
      - python3-apt
      - pelican
      - nginx


  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Install packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: '{{ packages }}'

  # - name: Install Pelican package
  #   pip:
  #     name:
  #       - pelican
  #       - Markdown
  
  - name: copy index.html
    template:
      src: templates/index.html.j2
      dest: /usr/share/nginx/html/index.html
      mode: 0644
    notify: restart nginx

  - name: copy nginx config file
    template:
      src: templates/nginxd.conf.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted