- name: Install packages
  hosts: webapp2
  remote_user: root
  become: yes
  # vars_files: playbook3_vars.yml

  tasks:
  - name: "Create blog directory"
    file:
      path: /home/azureuser/test_blog
      state: directory
  
  - name: Create Pelican command
    expect:
      command: pelican-quickstart
      responses:
        Where do you want to create your new web site?: "[/home/azureuser/test_blog/]"
        What will be the title of this web site?: "My Test Blog"
        Who will be the author of this web site?: "Damien"
        What will be the default language of this web site?: "[fr]"
        Do you want to specify a URL prefix?: "n"
        Do you want to enable article pagination?: "n"
        What is your time zone?: "[Europe/Paris]"
        Do you want to generate a tasks.py/Makefile to automate generation and publishing?: "n" 
        Do you want to upload your website using FTP?: "n"
        Do you want to upload your website using SSH?: "n"
        Do you want to upload your website using Dropbox?: "n"
        Do you want to upload your website using S3?: "n"
        Do you want to upload your website using Rackspace Cloud Files?: "n"
        Do you want to upload your website using GitHub Pages?: "n"