- name: PLAYBOOK3_Configuration of Pelican
  hosts: webapp2
  remote_user: root
  become: yes
  vars_files: ../playbook_vars.yml


  tasks:
  - name: "Create blog directory"
    file:
      path: "{{ path_blog }}"
      state: directory

  - name: Create Pelican command
    expect:
      command: pelican-quickstart
      responses:
        Where do you want to create your new web site?: "{{ path_blog }}"
        What will be the title of this web site?: "My Test Blog"
        Who will be the author of this web site?: "Damien"
        What will be the default language of this web site?: "\n"
        Do you want to specify a URL prefix?: "n"
        Do you want to enable article pagination?: "\n"
        How many articles per page do you want?: "\n"
        What is your time zone?: "\n"
        Do you want to generate a Fabfile/Makefile to automate generation and publishing?: "\n"
        Do you want an auto-reload & simpleHTTP script to assist with theme and site development?: "\n"
        Do you want to upload your website using FTP?: "\n"
        Do you want to upload your website using SSH?: "\n"
        Do you want to upload your website using Dropbox?: "\n"
        Do you want to upload your website using S3?: "\n"
        Do you want to upload your website using Rackspace Cloud Files?: "\n"
        Do you want to upload your website using GitHub Pages?: "\n"

  - name: "Copy file .md in content/"
    template:
      src: ../templates/test_blog.md.j2
      dest: "{{ path_blog }}/content/"

  - name: "Go to folder content and Create pelican blog"
    command: "chdir={{ path_blog }} sudo pelican content/"
    notify: restart nginx

  - name: "Register output folder variable"
    stat:
      path: "{{ path_blog }}/output"
    register: output
  
  - name: "Check that output folder exists"
    debug:
      msg: "Path exists and is a directory"
    when: output.stat.isdir is defined and output.stat.isdir
  

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted